[2024-05-01T16:20:30.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T16:20:30.826+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-01T16:03:13.237211+00:00 [queued]>
[2024-05-01T16:20:30.836+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-01T16:03:13.237211+00:00 [queued]>
[2024-05-01T16:20:30.836+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T16:20:30.847+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_wikipedia_data> on 2024-05-01 16:03:13.237211+00:00
[2024-05-01T16:20:30.852+0000] {standard_task_runner.py:63} INFO - Started process 3866 to run task
[2024-05-01T16:20:30.854+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'write_wikipedia_data', 'manual__2024-05-01T16:03:13.237211+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpwjq3v60j']
[2024-05-01T16:20:30.855+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask write_wikipedia_data
[2024-05-01T16:20:30.904+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-01T16:03:13.237211+00:00 [running]> on host ab8381b78bd9
[2024-05-01T16:20:31.083+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='write_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T16:03:13.237211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T16:03:13.237211+00:00'
[2024-05-01T16:20:31.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T16:20:31.108+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T16:20:31.109+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 123, in write_wikipedia_data
    data = json.load(data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
[2024-05-01T16:20:31.121+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=write_wikipedia_data, execution_date=20240501T160313, start_date=20240501T162030, end_date=20240501T162031
[2024-05-01T16:20:31.131+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task write_wikipedia_data ('str' object has no attribute 'read'; 3866)
[2024-05-01T16:20:31.146+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T16:20:31.165+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T16:20:31.167+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
