[2024-05-02T16:31:29.230+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T16:31:29.261+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-02T16:01:13.228158+00:00 [queued]>
[2024-05-02T16:31:29.270+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-02T16:01:13.228158+00:00 [queued]>
[2024-05-02T16:31:29.270+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-02T16:31:29.280+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_wikipedia_data> on 2024-05-02 16:01:13.228158+00:00
[2024-05-02T16:31:29.284+0000] {standard_task_runner.py:63} INFO - Started process 399 to run task
[2024-05-02T16:31:29.286+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'write_wikipedia_data', 'manual__2024-05-02T16:01:13.228158+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmptou5tt1d']
[2024-05-02T16:31:29.288+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask write_wikipedia_data
[2024-05-02T16:31:29.333+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.write_wikipedia_data manual__2024-05-02T16:01:13.228158+00:00 [running]> on host 18690b287db4
[2024-05-02T16:31:29.507+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='write_wikipedia_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T16:01:13.228158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T16:01:13.228158+00:00'
[2024-05-02T16:31:29.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T16:31:29.582+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T16:31:29.582+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 131, in write_wikipedia_data
    data.to_csv('abfs://footballdataeng@minhfootballproject.dfs.core.windows.get/data/' + filename,
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 430, in _get_filepath_or_buffer
    file_obj = fsspec.open(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 461, in open
    out = open_files(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 283, in open_files
    fs, fs_token, paths = get_fs_token_paths(
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 624, in get_fs_token_paths
    chain = _un_chain(urlpath0, storage_options or {})
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/core.py", line 332, in _un_chain
    cls = get_filesystem_class(protocol)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/registry.py", line 238, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/registry.py", line 273, in _import_class
    mod = importlib.import_module(mod)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.9/site-packages/adlfs/__init__.py", line 1, in <module>
    from .gen1 import AzureDatalakeFileSystem
  File "/home/airflow/.local/lib/python3.9/site-packages/adlfs/gen1.py", line 9, in <module>
    from azure.datalake.store import AzureDLFileSystem, lib
  File "/home/airflow/.local/lib/python3.9/site-packages/azure/datalake/store/__init__.py", line 11, in <module>
    from .core import AzureDLFileSystem
  File "/home/airflow/.local/lib/python3.9/site-packages/azure/datalake/store/core.py", line 27, in <module>
    from .lib import DatalakeRESTInterface
  File "/home/airflow/.local/lib/python3.9/site-packages/azure/datalake/store/lib.py", line 61, in <module>
    enforce_no_py_open_ssl()
  File "/home/airflow/.local/lib/python3.9/site-packages/azure/datalake/store/lib.py", line 42, in enforce_no_py_open_ssl
    from requests.packages.urllib3.contrib.pyopenssl import extract_from_urllib3
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    import OpenSSL.SSL  # type: ignore[import-untyped]
  File "/home/airflow/.local/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/airflow/.local/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1579, in <module>
    class X509StoreFlags(object):
  File "/home/airflow/.local/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1598, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
[2024-05-02T16:31:29.598+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=write_wikipedia_data, execution_date=20240502T160113, start_date=20240502T163129, end_date=20240502T163129
[2024-05-02T16:31:29.607+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task write_wikipedia_data (module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'; 399)
[2024-05-02T16:31:29.619+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T16:31:29.635+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T16:31:29.636+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
