[2024-04-29T17:07:30.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T17:07:30.799+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T17:07:26.396935+00:00 [queued]>
[2024-04-29T17:07:30.806+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T17:07:26.396935+00:00 [queued]>
[2024-04-29T17:07:30.806+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T17:07:30.815+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2024-04-29 17:07:26.396935+00:00
[2024-04-29T17:07:30.820+0000] {standard_task_runner.py:63} INFO - Started process 92 to run task
[2024-04-29T17:07:30.822+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2024-04-29T17:07:26.396935+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpwcwzz0qg']
[2024-04-29T17:07:30.823+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask extract_data_from_wikipedia
[2024-04-29T17:07:30.872+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2024-04-29T17:07:26.396935+00:00 [running]> on host 93901af84a11
[2024-04-29T17:07:30.956+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Minh Tran' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T17:07:26.396935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T17:07:26.396935+00:00'
[2024-04-29T17:07:30.957+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T17:07:31.488+0000] {logging_mixin.py:188} INFO - Getting wikipedia page... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2024-04-29T17:07:32.627+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T17:07:32.628+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 53, in extract_wikipedia_data
    data_df.to_csv("data/output.csv", index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'data/output.csv'
[2024-04-29T17:07:32.642+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20240429T170726, start_date=20240429T170730, end_date=20240429T170732
[2024-04-29T17:07:32.656+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task extract_data_from_wikipedia ([Errno 13] Permission denied: 'data/output.csv'; 92)
[2024-04-29T17:07:32.679+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T17:07:32.697+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T17:07:32.699+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
